package domain

import (
	"net/url"
	"regexp"
	"strings"
	"time"
)

// GitSource is an app's optional repository source. Private repositories are
// reached over SSH with a per-app deploy key generated by Bento; HTTPS is only
// for public repositories and never carries credentials.
type GitSource struct {
	RepoURL string `json:"repoUrl"`
	Branch  string `json:"branch"`
	// PrivateKey is the OpenSSH-encoded ed25519 deploy key. It never leaves
	// the backend except on exec stdin to a tooling container.
	PrivateKey     string    `json:"privateKey"`
	PublicKey      string    `json:"publicKey"`
	Fingerprint    string    `json:"fingerprint"`
	KeyCreatedAt   time.Time `json:"keyCreatedAt"`
	DeployedCommit string    `json:"deployedCommit,omitempty"`
	DeployedAt     time.Time `json:"deployedAt,omitzero"`
}

// UsesSSH reports whether the repository is fetched with the deploy key.
func (g GitSource) UsesSSH() bool { return !strings.HasPrefix(g.RepoURL, "https://") }

var (
	scpRepoPattern = regexp.MustCompile(`^[A-Za-z0-9_][A-Za-z0-9._-]*@[A-Za-z0-9][A-Za-z0-9.-]*:[A-Za-z0-9._~][A-Za-z0-9._~/-]*$`)
	branchPattern  = regexp.MustCompile(`^[A-Za-z0-9._/-]{1,200}$`)
	repoPathChars  = regexp.MustCompile(`^[A-Za-z0-9._~/-]+$`)
)

// ValidateGitSource checks a repository URL and branch. Accepted forms are
// user@host:path (scp-like SSH), ssh://user@host[:port]/path, and
// https://host/path for public repositories. Embedded HTTPS credentials are
// refused so secrets never reach argv, logs, or git config.
func ValidateGitSource(repoURL, branch string, errs *ValidationErrors) {
	switch {
	case repoURL == "":
		errs.Add("repoUrl", "is required")
	case len(repoURL) > 500:
		errs.Add("repoUrl", "is too long")
	case scpRepoPattern.MatchString(repoURL):
		if strings.Contains(repoURL, "..") {
			errs.Add("repoUrl", "must not contain '..'")
		}
	case strings.HasPrefix(repoURL, "ssh://"), strings.HasPrefix(repoURL, "https://"):
		u, err := url.Parse(repoURL)
		switch {
		case err != nil || u.Host == "" || u.Hostname() == "" || strings.HasPrefix(u.Hostname(), "-"):
			errs.Add("repoUrl", "is not a valid repository URL")
		case u.Scheme == "https" && u.User != nil:
			errs.Add("repoUrl", "must not embed credentials; use an SSH URL with the deploy key for private repositories")
		case u.Scheme == "ssh" && u.User != nil && func() bool { _, ok := u.User.Password(); return ok }():
			errs.Add("repoUrl", "must not embed a password")
		case u.RawQuery != "" || u.Fragment != "" || !repoPathChars.MatchString(strings.TrimPrefix(
			u.Path,
			"/",
		)) || strings.Contains(
			u.Path,
			"..",
		):
			errs.Add("repoUrl", "has an unsupported repository path")
		}
	default:
		errs.Add("repoUrl", "must be git@host:owner/repo.git, ssh://git@host/owner/repo.git, or https://host/owner/repo.git")
	}
	switch {
	case branch == "":
		errs.Add("branch", "is required")
	case !branchPattern.MatchString(branch), strings.HasPrefix(branch, "-"), strings.HasPrefix(branch, "/"),
		strings.HasSuffix(branch, "/"), strings.HasSuffix(branch, ".lock"), strings.Contains(branch, ".."),
		strings.Contains(branch, "//"), strings.HasSuffix(branch, "."):
		errs.Add("branch", "is not a valid branch name")
	}
}
